### ISSUE TITLE
Game Crash upon unphantomising with a Figura model that modifies arm rotation (Apugli v1.3.x, 1.18)

### ISSUE THREAD

**Issue by MerchantPug** [MerchantPug/apugli#2]
Read title.
Tested with Figura 0.0.8 rc.11+1.18

```
Time: 16/2/22, 8:34 am
Description: Unexpected error

java.util.NoSuchElementException
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
	at java.util.ArrayDeque.removeLast(ArrayDeque.java:372)
	at net.minecraft.client.util.math.MatrixStack.pop(MatrixStack:61)
	at net.minecraft.client.render.item.HeldItemRenderer.handler$zpa000$postRenderFirstPersonItem(HeldItemRenderer:1751)
	at net.minecraft.client.render.item.HeldItemRenderer.renderFirstPersonItem(HeldItemRenderer:588)
	at net.minecraft.client.render.item.HeldItemRenderer.redirect$zec000$renderModifiedItemFirstPersonMainhand(HeldItemRenderer:729)
	at net.minecraft.client.render.item.HeldItemRenderer.renderItem(HeldItemRenderer:364)
	at net.minecraft.client.render.GameRenderer.renderHand(GameRenderer:747)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1057)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:811)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by MerchantPug** [comment]
Fixed in local build, will push in a bit.
