### ISSUE TITLE
Game Crash on Entity Explosions

### ISSUE THREAD

**Issue by wrsgwergergwer** [MerchantPug/apugli#62]
> ---- Minecraft Crash Report ----
>
>// Hey, that tickles! Hehehe!
>
>Time: 2023-11-13 19:13:38
>Description: Ticking entity
>
>java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1927 failed
	>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_1937.method_46668(class_1937.java:535)
	at net.minecraft.class_3218.method_8454(class_3218.java:1059)
	at net.minecraft.class_1937.method_8437(class_1937.java:511)
	at net.minecraft.class_1541.method_6971(class_1541.java:98)
	at net.minecraft.class_1541.method_5773(class_1541.java:86)
	at net.minecraft.class_3218.method_18762(class_3218.java:745)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:820)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 20 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_1927::method_8348()V has incompatible changes at opcode 450 in callback apugli.mixins.json:common.ExplosionMixin from mod apugli->@Inject::apugli$collectAffectedEntity(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Ljava/util/Set;IFIIIIIILjava/util/List;Lnet/minecraft/class_243;ILnet/minecraft/class_1297;)V.
 Expected: [Ljava/util/Set;, I, F, I, I, I, I, I, I, Ljava/util/List;, Lnet/minecraft/class_243;, I, Lnet/minecraft/class_1297;]
    Found: [Ljava/util/Set;, I, F, I, I, I, I, I, I, Ljava/util/List;, Lnet/minecraft/class_243;, Ljava/util/Iterator;, Lnet/minecraft/class_1297;]
Available: [Ljava/util/Set;, I, F, I, I, I, I, I, I, Ljava/util/List;, Lnet/minecraft/class_243;, Ljava/util/Iterator;, Lnet/minecraft/class_1297;]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:547)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 23 more
	
This happens whenever any entity explodes, this test was done on a fresh 1.20.2 instance with just Fabric API, Apoli & Apugli

**Comment by ChrysanthCow** [comment]
Should be fixed in 2.8.1, I've swapped to a different method for getting the entity for the explosion.

**Comment by wrsgwergergwer** [comment]
Sweet, thanks for the fast rsponse, though now theres a new injection issue: 
>Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method apugli$dontAngerBees(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Ljava/util/List;Ljava/util/List;)V in apugli.mixins.json:common.BeehiveBlockMixin from mod apugli failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap apugli.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[minecraft-1.20.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	... 10 more

Edit: Im blind, didnt notice that new release is for 1.20.1, this can be safely disregarded if theres a 1.20.2 one coming

**Comment by ChrysanthCow** [comment]
That's extremely weird, could you send the full logs?

**Comment by ChrysanthCow** [comment]
I'll probably just adjust the mixin location for the time being and see if that fixes it.

**Comment by wrsgwergergwer** [comment]
> That's extremely weird, could you send the full logs?

Heres the full log of a launch attempt with the new version https://pastebin.com/VTWW2U1f

**Comment by ChrysanthCow** [comment]
Alright, I've made an attempted fix. 2.8.1 will be soon.

**Comment by ChrysanthCow** [comment]
2.8.1 for 1.20.2 has been released.

**Comment by wrsgwergergwer** [comment]
Seems like this push fixed all the issues, game boots up fine now and so far Ive not encountered any crashes, thanks for taking the time to fix this!
