### ISSUE TITLE
Game suddenly crash when playing origin using apugli

### ISSUE THREAD

**Issue by AofTHz** [MerchantPug/apugli#73]
I was using Origins: Volcanic Dragon, i was able to play for sometime but suddenly game crashed, i often happened when i about to open inventory

```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-03-08 04:06:26
Description: Ticking player

java.lang.NullPointerException: Cannot invoke "net.merchantpug.apugli.access.ItemStackAccess.apugli$getEntity()" because "self" is null
	at net.merchantpug.apugli.power.factory.ModifyEnchantmentLevelPowerFactory.getEnchantments(ModifyEnchantmentLevelPowerFactory.java:151)
	at net.minecraft.class_1890.localvar$eon000$apugli$getEnchantmentsGetLevel(class_1890.java:2058)
	at net.minecraft.class_1890.method_8225(class_1890.java:71)
	at net.minecraft.class_1890.method_8203(class_1890.java:195)
	at net.minecraft.class_1309.method_6126(class_1309.java:564)
	at net.minecraft.class_3222.method_6126(class_3222.java:994)
	at net.minecraft.class_1309.method_5670(class_1309.java:421)
	at net.minecraft.class_1297.method_5773(class_1297.java:474)
	at net.minecraft.class_1309.method_5773(class_1309.java:2380)
	at net.minecraft.class_1657.method_5773(class_1657.java:283)
	at net.minecraft.class_3222.method_14226(class_3222.java:510)
	at net.minecraft.class_3244.mixinextras$bridge$method_14226$150(class_3244.java)
	at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickPlayer$notTheCauseOfTickLag(NeruinaTickHandler.java:63)
	at net.minecraft.class_3244.wrapOperation$zlb000$neruina$catchTickingPlayer(class_3244.java:3454)
	at net.minecraft.class_3244.method_18784(class_3244.java:269)
	at net.minecraft.class_2535.method_10754(class_2535.java:259)
	at net.minecraft.class_3242.method_14357(class_3242.java:172)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.merchantpug.apugli.power.factory.ModifyEnchantmentLevelPowerFactory.getEnchantments(ModifyEnchantmentLevelPowerFactory.java:151)
	at net.minecraft.class_1890.localvar$eon000$apugli$getEnchantmentsGetLevel(class_1890.java:2058)
	at net.minecraft.class_1890.method_8225(class_1890.java:71)
	at net.minecraft.class_1890.method_8203(class_1890.java:195)
	at net.minecraft.class_1309.method_6126(class_1309.java:564)
	at net.minecraft.class_3222.method_6126(class_3222.java:994)
	at net.minecraft.class_1309.method_5670(class_1309.java:421)
	at net.minecraft.class_1297.method_5773(class_1297.java:474)
	at net.minecraft.class_1309.method_5773(class_1309.java:2380)
	at net.minecraft.class_1657.method_5773(class_1657.java:283)
	at net.minecraft.class_3222.method_14226(class_3222.java:510)
	at net.minecraft.class_3244.mixinextras$bridge$method_14226$150(class_3244.java)
	at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickPlayer$notTheCauseOfTickLag(NeruinaTickHandler.java:63)
	at net.minecraft.class_3244.wrapOperation$zlb000$neruina$catchTickingPlayer(class_3244.java:3454)
	at net.minecraft.class_3244.method_18784(class_3244.java:269)
	at net.minecraft.class_2535.method_10754(class_2535.java:259)
	at net.minecraft.class_3242.method_14357(class_3242.java:172)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 1
	Entity Name: conteenTH
	Entity's Exact location: 178.00, 43.00, -265.75
	Entity's Block location: World: (177,43,-266), Section: (at 1,11,6 in 11,2,-17; chunk contains blocks 176,0,-272 to 191,255,-257), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: -0.01, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_3222.method_14226(class_3222.java:510)
	at net.minecraft.class_3244.mixinextras$bridge$method_14226$150(class_3244.java)
	at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickPlayer$notTheCauseOfTickLag(NeruinaTickHandler.java:63)
	at net.minecraft.class_3244.wrapOperation$zlb000$neruina$catchTickingPlayer(class_3244.java:3454)
	at net.minecraft.class_3244.method_18784(class_3244.java:269)
	at net.minecraft.class_2535.method_10754(class_2535.java:259)
	at net.minecraft.class_3242.method_14357(class_3242.java:172)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Wrapped in --
Details:
	Wrapping exception: ~~ERROR~~ class_148: Ticking memory connection
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_40376(MinecraftServer.java:729)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by ChrysanthCow** [comment]
Hi, which modloader and which mod version are you on?

**Comment by AofTHz** [comment]
Quilit loader 0.24.0-beta8 1.20.1

**Comment by ChrysanthCow** [comment]
Alright, which Apugli version are you on?

**Comment by AofTHz** [comment]
Fabric/Quilt v2.10.0+1.20.1

It also crashed on fabric too, i tried few moment ago

**Comment by ChrysanthCow** [comment]
Okay, that's enough information. I'll look into a fix at some date.
