### ISSUE TITLE
Apugli / Apoli 1.19.2 server crash

### ISSUE THREAD

**Issue by AWildWarrior** [MerchantPug/apugli#77]
Server keeps crashing and i have no idea why, the only thing i know is that Apugli / Apoli is crashing the server.
crash report:
<html>
<body>

1 | ---- Minecraft Crash Report ----
-- | --
2 | // On the bright side, I bought you a teddy bear!
3 |  
4 | Time: 2024-04-01 22:41:37
5 | Description: Exception ticking world
6 |  
7 | java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.equals(Object)" because "this.lootTableId" is null
8 | at net.minecraft.world.level.storage.loot.LootTable.handler$zdc000$setReplacedLootTable(LootTable.java:595) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading,pl:mixin:A}
9 | at net.minecraft.world.level.storage.loot.LootTable.m_79131_(LootTable.java) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading,pl:mixin:A}
10 | at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:84) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading,pl:mixin:A}
11 | at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:89) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading,pl:mixin:A}
12 | at net.minecraft.world.level.block.state.BlockBehaviour.m_7381_(BlockBehaviour.java:253) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:forge.BlockBehaviourMixin,pl:mixin:A}
13 | at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60724_(BlockBehaviour.java:710) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading,pl:mixin:APP:apoli.mixins.json:AbstractBlockStateMixin,pl:mixin:A}
14 | at net.minecraft.world.level.block.Block.m_49869_(Block.java:257) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury-common.mixins.json:inject.MixinBlock,pl:mixin:A}
15 | at net.minecraft.world.level.block.Block.m_49892_(Block.java:286) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury-common.mixins.json:inject.MixinBlock,pl:mixin:A}
16 | at net.minecraft.world.level.material.WaterFluid.m_7456_(WaterFluid.java:69) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading}
17 | at net.minecraft.world.level.material.FlowingFluid.m_6364_(FlowingFluid.java:246) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,re:mixin}
18 | at net.minecraft.world.level.material.FlowingFluid.m_76014_(FlowingFluid.java:145) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,re:mixin}
19 | at net.minecraft.world.level.material.FlowingFluid.m_76010_(FlowingFluid.java:124) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,re:mixin}
20 | at net.minecraft.world.level.material.FlowingFluid.m_6292_(FlowingFluid.java:415) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,re:mixin}
21 | at net.minecraft.world.level.material.FluidState.m_76163_(FluidState.java:76) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading}
22 | at net.minecraft.world.level.chunk.LevelChunk.m_62812_(LevelChunk.java:490) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B}
23 | at net.minecraft.server.level.ChunkMap.m_214959_(ChunkMap.java:724) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B}
24 | at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[datafixerupper-5.0.28.jar%2375!/:?] {}
25 | at net.minecraft.server.level.ChunkMap.m_214929_(ChunkMap.java:723) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B}
26 | at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?] {}
27 | at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
28 | at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
29 | at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:535) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading}
30 | at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
31 | at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:543) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading}
32 | at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:267) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
33 | at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:751) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
34 | at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
35 | at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
36 | at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
37 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
38 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
39 | at java.lang.Thread.run(Thread.java:840) [?:?] {}
40 |  
41 |  
42 | A detailed walkthrough of the error, its code path and all known details is as follows:
43 | ---------------------------------------------------------------------------------------
44 |  
45 | -- Head --
46 | Thread: Server thread
47 | Stacktrace:
48 | at net.minecraft.world.level.storage.loot.LootTable.handler$zdc000$setReplacedLootTable(LootTable.java:595) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading,pl:mixin:A}
49 | at net.minecraft.world.level.storage.loot.LootTable.m_79131_(LootTable.java) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading,pl:mixin:A}
50 | at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:84) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading,pl:mixin:A}
51 | at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:89) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading,pl:mixin:A}
52 | at net.minecraft.world.level.block.state.BlockBehaviour.m_7381_(BlockBehaviour.java:253) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:forge.BlockBehaviourMixin,pl:mixin:A}
53 | at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60724_(BlockBehaviour.java:710) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading,pl:mixin:APP:apoli.mixins.json:AbstractBlockStateMixin,pl:mixin:A}
54 | at net.minecraft.world.level.block.Block.m_49869_(Block.java:257) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury-common.mixins.json:inject.MixinBlock,pl:mixin:A}
55 | at net.minecraft.world.level.block.Block.m_49892_(Block.java:286) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury-common.mixins.json:inject.MixinBlock,pl:mixin:A}
56 | at net.minecraft.world.level.material.WaterFluid.m_7456_(WaterFluid.java:69) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading}
57 | at net.minecraft.world.level.material.FlowingFluid.m_6364_(FlowingFluid.java:246) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,re:mixin}
58 | at net.minecraft.world.level.material.FlowingFluid.m_76014_(FlowingFluid.java:145) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,re:mixin}
59 | at net.minecraft.world.level.material.FlowingFluid.m_76010_(FlowingFluid.java:124) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,re:mixin}
60 | at net.minecraft.world.level.material.FlowingFluid.m_6292_(FlowingFluid.java:415) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,re:mixin}
61 | at net.minecraft.world.level.material.FluidState.m_76163_(FluidState.java:76) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading}
62 | at net.minecraft.world.level.chunk.LevelChunk.m_62812_(LevelChunk.java:490) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B}
63 | at net.minecraft.server.level.ChunkMap.m_214959_(ChunkMap.java:724) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B}
64 | at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[datafixerupper-5.0.28.jar%2375!/:?] {}
65 | at net.minecraft.server.level.ChunkMap.m_214929_(ChunkMap.java:723) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B}
66 | at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?] {}
67 | at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
68 | at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
69 | at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:535) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading}
70 | at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
71 | at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:543) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading}
72 | at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:267) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
73 | at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:751) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
74 | -- Affected level --
75 | Details:
76 | All players: 1 total; [ServerPlayer['AWildWarrior'/773, l='ServerLevel[world]', x=706.39, y=64.00, z=67.63]]
77 | Chunk stats: 2908
78 | Level dimension: minecraft:overworld
79 | Level spawn location: World: (448,66,-160), Section: (at 0,2,0 in 28,4,-10; chunk contains blocks 448,-64,-160 to 463,319,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
80 | Level time: 1597021 game time, 1566723 day time
81 | Level name: world
82 | Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
83 | Level weather: Rain time: 18987 (now: true), thunder time: 64715 (now: false)
84 | Known server brands: forge
85 | Level was modded: true
86 | Level storage version: 0x04ABD - Anvil
87 | Stacktrace:
88 | at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:869) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
89 | at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:A}
90 | at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
91 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
92 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
93 | at java.lang.Thread.run(Thread.java:840) [?:?] {}

</body>
</html>---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 2024-04-0[1](https://aternos.org/files/crash-reports/crash-2024-04-01_22.41.37-server.txt#L1) 22:41:37
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.equals(Object)" because "this.lootTableId" is null
	at net.minecraft.world.level.storage.loot.LootTable.handler$zdc000$setReplacedLootTable(LootTable.java:595) ~[server-1.19.[2](https://aternos.org/files/crash-reports/crash-2024-04-01_22.41.37-server.txt#L2)-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.world.level.storage.loot.LootTable.m_791[3](https://aternos.org/files/crash-reports/crash-2024-04-01_22.41.37-server.txt#L3)1_(LootTable.java) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.world.level.storage.loot.LootTable.m_791[4](https://aternos.org/files/crash-reports/crash-2024-04-01_22.41.37-server.txt#L4)8_(LootTable.java:84) ~[server-1.19.2-2022080[5](https://aternos.org/files/crash-reports/crash-2024-04-01_22.41.37-server.txt#L5).130853-srg.jar%23169!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:89) ~[server-1.19.2-20220805.130853-srg.jar%231[6](https://aternos.org/files/crash-reports/crash-2024-04-01_22.41.37-server.txt#L6)9!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.world.level.block.state.BlockBehaviour.m_[7](https://aternos.org/files/crash-reports/crash-2024-04-01_22.41.37-server.txt#L7)381_(BlockBehaviour.java:253) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:forge.BlockBehaviourMixin,pl:mixin:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60724_(BlockBehaviour.java:710) ~[server-1.19.2-20220[8](https://aternos.org/files/crash-reports/crash-2024-04-01_22.41.37-server.txt#L8)05.130853-srg.jar%23169!/:?] {re:mixin,re:classloading,pl:mixin:APP:apoli.mixins.json:AbstractBlockStateMixin,pl:mixin:A}
	at net.minecraft.world.level.block.Block.m_49869_(Block.java:257) ~[server-1.1[9](https://aternos.org/files/crash-reports/crash-2024-04-01_22.41.37-server.txt#L9).2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury-common.mixins.json:inject.MixinBlock,pl:mixin:A}
	at net.minecraft.world.level.block.Block.m_49892_(Block.java:286) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury-common.mixins.json:inject.MixinBlock,pl:mixin:A}
	at net.minecraft.world.level.material.WaterFluid.m_7456_(WaterFluid.java:69) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading}
	at net.minecraft.world.level.material.FlowingFluid.m_6364_(FlowingFluid.java:246) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.level.material.FlowingFluid.m_76014_(FlowingFluid.java:145) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.level.material.FlowingFluid.m_760[10](https://aternos.org/files/crash-reports/crash-2024-04-01_22.41.37-server.txt#L10)_(FlowingFluid.java:124) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.level.material.FlowingFluid.m_6292_(FlowingFluid.java:415) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.level.material.FluidState.m_76163_(FluidState.java:76) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk.m_62812_(LevelChunk.java:490) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.m_214959_(ChunkMap.java:724) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B}
	at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[datafixerupper-5.0.28.jar%2375!/:?] {}
	at net.minecraft.server.level.ChunkMap.m_214929_(ChunkMap.java:723) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:535) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:543) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading}
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:267) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:751) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:[11](https://aternos.org/files/crash-reports/crash-2024-04-01_22.41.37-server.txt#L11)6) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_1300[12](https://aternos.org/files/crash-reports/crash-2024-04-01_22.41.37-server.txt#L12)_(MinecraftServer.java:725) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.[13](https://aternos.org/files/crash-reports/crash-2024-04-01_22.41.37-server.txt#L13)0853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.level.storage.loot.LootTable.handler$zdc000$setReplacedLootTable(LootTable.java:595) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.world.level.storage.loot.LootTable.m_79131_(LootTable.java) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.world.level.storage.loot.LootTable.m_79[14](https://aternos.org/files/crash-reports/crash-2024-04-01_22.41.37-server.txt#L14)8_(LootTable.java:84) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:89) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.world.level.block.state.BlockBehaviour.m_7381_(BlockBehaviour.java:253) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:forge.BlockBehaviourMixin,pl:mixin:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60724_(BlockBehaviour.java:710) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading,pl:mixin:APP:apoli.mixins.json:AbstractBlockStateMixin,pl:mixin:A}
	at net.minecraft.world.level.block.Block.m_49869_(Block.java:257) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury-common.mixins.json:inject.MixinBlock,pl:mixin:A}
	at net.minecraft.world.level.block.Block.m_49892_(Block.java:286) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury-common.mixins.json:inject.MixinBlock,pl:mixin:A}
	at net.minecraft.world.level.material.WaterFluid.m_7456_(WaterFluid.java:69) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading}
	at net.minecraft.world.level.material.FlowingFluid.m_6364_(FlowingFluid.java:246) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.level.material.FlowingFluid.m_76014_(FlowingFluid.java:145) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.level.material.FlowingFluid.m_76010_(FlowingFluid.java:124) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.level.material.FlowingFluid.m_6292_(FlowingFluid.java:4[15](https://aternos.org/files/crash-reports/crash-2024-04-01_22.41.37-server.txt#L15)) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.level.material.FluidState.m_76163_(FluidState.java:76) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk.m_62812_(LevelChunk.java:490) ~[server-1.19.2-20220805.130853-srg.jar%23[16](https://aternos.org/files/crash-reports/crash-2024-04-01_22.41.37-server.txt#L16)9!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.m_214959_(ChunkMap.java:724) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B}
	at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[datafixerupper-5.0.28.jar%2375!/:?] {}
	at net.minecraft.server.level.ChunkMap.m_214929_(ChunkMap.java:723) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:535) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:543) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading}
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:267) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:751) ~[server-1.19.2-20220805.130853-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}

**Comment by ChrysanthCow** [comment]
Known Origins Forge issue, downgrade Origins for the time being, I'll get to fixing this in Origins Forge's next 1.19.2 update.
