### ISSUE TITLE
Ticking entity error causes server crash on load-in

### ISSUE THREAD

**Issue by EnglishNarwhal** [MerchantPug/apugli#80]
Forge Server v43.3.0 runs fine until someone attempts to load in, resulting in the crash below. Should be noted this is the Apugli version packaged with TMO Forge v1.0.0-beta.19+1.19.2; if this is more pertinent to TMO let me know and I'll push it to them.

The entity it identifies is a zombie with the vehicle 'null', and it cites apugli. Not sure where to go from there.

`Time: 2024-07-05 23:00:08
Description: Ticking entity

java.lang.NullPointerException: Cannot read field "f_19853_" because "entity" is null
	at net.merchantpug.apugli.condition.factory.entity.EntityInRadiusCondition.check(EntityInRadiusCondition.java:38) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at net.merchantpug.apugli.condition.factory.entity.EntityInRadiusCondition.check(EntityInRadiusCondition.java:14) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at net.merchantpug.apugli.condition.configuration.FabricConditionConfiguration.lambda$codec$0(FabricConditionConfiguration.java:13) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at net.merchantpug.apugli.condition.FabricEntityCondition.check(FabricEntityCondition.java:20) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at net.merchantpug.apugli.condition.FabricEntityCondition.check(FabricEntityCondition.java:11) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.factory.EntityCondition.check(EntityCondition.java:34) ~[apoli-forge-1.19.2-2.6.1.7.jar%23465!/:1.19.2-2.6.1.7] {re:classloading,re:mixin}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredEntityCondition.check(ConfiguredEntityCondition.java:42) ~[apoli-forge-1.19.2-2.6.1.7.jar%23465!/:1.19.2-2.6.1.7] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.bientity.DispatchBiEntityCondition.lambda$new$4(DispatchBiEntityCondition.java:36) ~[apoli-forge-1.19.2-2.6.1.7.jar%23465!/:1.19.2-2.6.1.7] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.bientity.DispatchBiEntityCondition.check(DispatchBiEntityCondition.java:41) ~[apoli-forge-1.19.2-2.6.1.7.jar%23465!/:1.19.2-2.6.1.7] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.condition.bientity.DispatchBiEntityCondition.check(DispatchBiEntityCondition.java:10) ~[apoli-forge-1.19.2-2.6.1.7.jar%23465!/:1.19.2-2.6.1.7] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.factory.BiEntityCondition.check(BiEntityCondition.java:32) ~[apoli-forge-1.19.2-2.6.1.7.jar%23465!/:1.19.2-2.6.1.7] {re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredBiEntityCondition.check(ConfiguredBiEntityCondition.java:42) ~[apoli-forge-1.19.2-2.6.1.7.jar%23465!/:1.19.2-2.6.1.7] {re:classloading}
	at net.merchantpug.apugli.platform.ForgeConditionHelper.checkBiEntity(ForgeConditionHelper.java:47) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at net.merchantpug.apugli.power.factory.DamageNearbyPowerFactory.execute(DamageNearbyPowerFactory.java:30) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at net.merchantpug.apugli.power.factory.DamageNearbyWhenHitPowerFactory.execute(DamageNearbyWhenHitPowerFactory.java:18) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at net.merchantpug.apugli.ApugliForgeEventHandler.lambda$onLivingHurt$11(ApugliForgeEventHandler.java:211) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at net.merchantpug.apugli.ApugliForgeEventHandler.onLivingHurt(ApugliForgeEventHandler.java:211) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading}
	at net.merchantpug.apugli.__ApugliForgeEventHandler_onLivingHurt_LivingHurtEvent.invoke(.dynamic) ~[Apugli-2.6.6+1.19.2-forge.jar%23468!/:2.6.6+1.19.2-forge] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:343) ~[forge-1.19.2-43.3.0-universal.jar%23408!/:?] {re:mixin,re:classloading,pl:mixin:APP:apoli.mixins.json:forge.ForgeHooksMixin,pl:mixin:APP:tombstone.mixins.json:ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_6475_(LivingEntity.java:1578) ~[server-1.19.2-20220805.130853-srg.jar%23403!/:?]`
	
It goes on from here, and I've attached the full file minus system information:

[crash-2024-07-05_23.00.08-server.txt](https://github.com/user-attachments/files/16116903/crash-2024-07-05_23.00.08-server.txt)

**Comment by EnglishNarwhal** [comment]
Fixed the problem by killing all the mobs, and the server crashed when I killed a zombie with lightning breath from TMO. This is likely a TMO issue instead, then, and I'll make the complaint there.

**Comment by ChrysanthCow** [comment]
I made TMO too, so you've got the right person. I'll be fixing this in a bit.

You were correct for it being an Apugli issue, it was just exposed by TooManyOrigins.

Sorry for the wait!
