### ISSUE TITLE
Apparent incompatibility with TACZ (successor mod to Tactics and Combat, gun mod) in 1.20.1

### ISSUE THREAD

**Issue by james5922** [MerchantPug/apugli#83]
Trying to put together a custom modpack using Quantum Freedom 2 as a base.

Added TACZ (a gun mod, successor to the old "Tactics and Combat") to the pack previously, when I attempted to add Apugli (due to it being a dependency for Arcadian Dream/Touhou Origins' 1.20.1 version) it no longer loads.

Not sure if this is a TACZ problem or an Apugli problem.
Given it seems to be linked to rendering, I suppose I should mention that I'm on Windows 10, using a fairly modern NVIDIA GPU (RTX 3050) and AMD CPU (Ryzen 5 5600G).

Relevant bit from log: 
```
[11:54:02] [Render thread/WARN]: @Redirect conflict. Skipping tacz.mixins.json:client.HeldItemRendererMixin from mod tacz->@Redirect::renderFirstPersonItemMainHand(Lnet/minecraft/class_759;Lnet/minecraft/class_742;FFLnet/minecraft/class_1268;FLnet/minecraft/class_1799;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;I)V with priority 1000, already redirected by apugli.mixins.json:client.HeldItemRendererMixin from mod apugli->@Redirect::apugli$renderModifiedItemFirstPersonMainhand(Lnet/minecraft/class_759;Lnet/minecraft/class_742;FFLnet/minecraft/class_1268;FLnet/minecraft/class_1799;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;I)V with priority 1000
[11:54:02] [Render thread/WARN]: @Redirect conflict. Skipping tacz.mixins.json:client.HeldItemRendererMixin from mod tacz->@Redirect::renderFirstPersonItemMainHand(Lnet/minecraft/class_759;Lnet/minecraft/class_742;FFLnet/minecraft/class_1268;FLnet/minecraft/class_1799;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;I)V with priority 1000, already redirected by apugli.mixins.json:client.HeldItemRendererMixin from mod apugli->@Redirect::apugli$renderModifiedItemFirstPersonOffhand(Lnet/minecraft/class_759;Lnet/minecraft/class_742;FFLnet/minecraft/class_1268;FLnet/minecraft/class_1799;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;I)V with priority 1000
[11:54:02] [Render thread/INFO]: [FastQuit] Exiting FastQuit.
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-09-17 11:54:02
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_759 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.class_898.<init>(class_898.java:86)
	at net.minecraft.class_310.<init>(class_310.java:577)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 16 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector renderFirstPersonItemMainHand(Lnet/minecraft/class_759;Lnet/minecraft/class_742;FFLnet/minecraft/class_1268;FLnet/minecraft/class_1799;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;I)V in tacz.mixins.json:client.HeldItemRendererMixin from mod tacz failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap tacz-fabric-1.20.1-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 19 more

[trim]

	Fabric Mods: 
		ad_astra: Ad Astra 1.15.18
			javazoom_jlayer: jlayer 1.0.1
		ad_astra_giselle_addon: Ad Astra: Giselle Addon 6.5
		advanced_reborn: Advanced Reborn 1.2.8
		ae2: Applied Energistics 2 15.2.12
			team_reborn_energy: Energy 3.0.0
		ae2wtlib: AE2WTLib 15.2.1-fabric
		alloy_forgery: Alloy Forgery 2.1.2+1.20
		amendments: Amendments 1.20-1.2.11
			mixinextras: MixinExtras 0.3.6
		appbot: Applied Botanics 1.5.0
		appleskin: AppleSkin 2.5.1+mc1.20
		apugli: Apugli 2.10.4+1.20.1-fabric
		arcadiandream: Arcadian Dream 0.1.0
		architectury: Architectury 9.2.14
		argonauts: Argonauts 1.0.10
		automobility: Automobility 0.4.2+1.20.1-fabric
			jsonem: JsonEM 0.2.1+1.20
		azurelib: AzureLib 2.0.35
		bakery: [Let's Do] Bakery 1.1.15
		balm-fabric: Balm 7.3.9
			kuma_api: KumaAPI 20.1.8
		beachparty: [Let's Do] Beachparty 1.1.5
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.4
		betterendisland: YUNG's Better End Island 1.20-Fabric-2.0.6
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.6
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.5
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		bewitchment: Bewitchment 1.20-8
			impersonate: Impersonate 2.10.2
			playerabilitylib: Pal 1.8.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.3
		bookshelf: Bookshelf 20.2.13
		botania: Botania 1.20.1-446-FABRIC
			fiber: fiber 0.23.0-2
		botanypots: BotanyPots 13.0.39
		botarium: Botarium 2.3.4
		brewery: [Let's Do] Brewery 1.1.9
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.13
			[trimmed c2me sub-mods]
		candlelight: [Let's Do] Candlelight 1.2.13
		capes: Capes 1.5.2+1.20
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		cinderscapes: Cinderscapes 4.0.10
			biolith: Biolith 1.0.0-beta.1
			cinderscapes-client: Cinderscapes: Client 4.0.10
			cinderscapes-common: Cinderscapes: Common 4.0.10
			cinderscapes-worldgen: Cinderscapes: World Generation 4.0.10
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 7.0.3
			terraform-shapes-api-v1: Terraform Shapes API (v1) 7.0.3
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 7.0.3
		cloth-config: Cloth Config v11 11.1.136
			cloth-basic-math: cloth-basic-math 0.6.1
		computercraft: CC: Tweaked 1.113.1
			cc_tweaked_cobalt: cobalt 0.9.3
			com_jcraft_jzlib: jzlib 1.1.3
			io_netty_netty-codec-http: netty-codec-http 4.1.82
			io_netty_netty-codec-socks: netty-codec-socks 4.1.82
			io_netty_netty-handler-proxy: netty-handler-proxy 4.1.82
		continuity: Continuity 3.0.0-beta.5+1.20.1
		controlling: Controlling For Fabric 12.0.2
		cosmetic-armor: Cosmetic Armor 1.6.0
		craterlib: CraterLib 2.1.0
		create: Create 0.5.1-f-build.1417+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.2+1.20.1
			porting_lib_base: Porting Lib Base 2.3.2+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.2+1.20.1
				porting_lib_common: Porting Lib Common 2.3.2+1.20.1
				porting_lib_config: Porting Lib Config 2.3.2+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.2+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.2+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.2+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.2+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.2+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.2+1.20.1
			porting_lib_models: Porting Lib Models 2.3.2+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.2+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.2+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.2+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.2+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.2+1.20.1
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		createdeco: Create Deco 2.0.2-1.20.1-fabric
		defaultoptions: Default Options 18.0.1
		diggusmaximus: Diggus Maximus 1.5.9-1.20
			kyrptconfig: Kyrpt Config 1.5.6-1.20
		doapi: [Let's Do] API 1.2.15
		drippyloadingscreen: Drippy Loading Screen 3.0.2
		dynamic_fps: Dynamic FPS 3.7.1
			net_lostluma_battery: battery 1.1.0
		emojiful: Emojiful 4.2.0
			com_esotericsoftware_yamlbeans_yamlbeans: yamlbeans 1.15
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entangled: Entangled 1.3.19
		entityculling: EntityCulling 1.7.0
		essential_commands: Essential Commands 0.35.3-mc1.20.1
			ec-core: Essential Commands Core 1.3.0-mc1.20.1
		exordium: Exordium 1.2.1-mc1.20.1
		expandedstorage: Expanded Storage 10.3.0-beta.5
		extended_drawers: Extended Drawers 2.1.1+mc.1.20.1
			config_toolkit: ConfigToolkit 1.0.0
				io_determann_shadow-api-17: shadow-api-17 0.1.1
				net_fabricmc_javapoet: javapoet 0.1.0
			graphlib: Graph Lib 1.4.0+1.20
				kmodlib-overlay: KModLib Overlay 0.2.12+1.20
				libnetworkstack: Lib Network Stack 0.10.0
			noindium: No Indium? 1.1.0+1.20
			yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20
				com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
				com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
				com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
				org_quiltmc_parsers_gson: gson 0.2.1
				org_quiltmc_parsers_json: json 0.2.1
		fabric-api: Fabric API 0.92.2+1.20.1
			[trimmed Fabric API sub-mods]
		fabric-language-kotlin: Fabric Language Kotlin 1.12.1+kotlin.2.0.20
			[trimmed Kotlin sub-mods]
		fabricloader: Fabric Loader 0.15.11
		fallingtree: FallingTree 4.3.4
		fancymenu: FancyMenu 3.2.3
			com_github_keksuccino_japng: japng 0.5.3
			com_github_rtyley_animated-gif-lib-for-java: animated-gif-lib-for-java animated-gif-lib-1.7
		fastquit: FastQuit 3.0.0+1.20+
		ferritecore: FerriteCore 6.0.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		friendsandfoes: Friends&Foes 2.0.17
		frostiful: Frostiful 1.0.11
			mm: Manningham Mills 2.3
		fusion: Fusion 1.1.1
		geckolib: GeckoLib 4 4.4.9
			com_eliotlash_mclib_mclib: mclib 20
		graveyard: The Graveyard 3.0
		herbalbrews: [Let's Do] HerbalBrews 1.0.8.1
		immediatelyfast: ImmediatelyFast 1.2.21+1.20.4
			net_lenni0451_reflect: Reflect 1.3.4
		indium: Indium 1.0.34+mc1.20.1
		inventorysorter: Inventory Sorter 1.9.0-1.20
		iris: Iris 1.7.2+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		jade: Jade 11.11.0+fabric
		java: Java HotSpot(TM) 64-Bit Server VM 22
		konkrete: Konkrete 1.8.1
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		letmedespawn: Let Me Despawn 1.2.1
		lexiconfig: Lexiconfig 1.3.11
		lithium: Lithium 0.11.2
		lmft: Load My F***ing Tags 1.0.2+1.20
		loadmyresources: Load My Resources 1.0.4
		lootr: Lootr 0.7.33.81
		mcpitanlib: MCPitanLib 2.4.4-1.20.1-fabric
		meadow: [Let's Do] Meadow 1.3.19
			mixinsquared: MixinSquared 0.1.2-beta.5
		melody: Melody 1.0.3
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		modern_industrialization: Modern Industrialization 1.8.6
			magna: Magna 1.10.1+1.20.1
				omega-config: OmegaConfig 1.0.8
		moderndynamics: Modern Dynamics 0.7.0-beta
		modernfix: ModernFix 5.19.4+mc1.20.1
		modmenu: Mod Menu 7.2.2
		moonlight: Moonlight 1.20-2.12.21
		moreculling: More Culling 1.20.4-0.24.0
			conditional-mixin: conditional mixin 0.3.2
		mousetweaks: Mouse Tweaks 2.26
		nethervinery: [Let's Do] NetherVinery 1.2.14
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		noisium: Noisium 2.3.0+mc1.20-1.20.1
		opaccreatesupport: OPAC Create Mod Support 1.6.0
		openpartiesandclaims: Open Parties and Claims 0.23.2
		origins: Origins 1.10.0
			apoli: Apoli 2.9.0
				additionalentityattributes: Additional Entity Attributes 1.3.0+1.20.0
				calio: Calio 1.11.0
		owo: o?o 0.11.2+1.20
			blue_endless_jankson: jankson 1.2.2
		packetfixer: Packet Fixer 1.4.2
		patchouli: Patchouli 1.20.1-84-FABRIC
		pehkui: Pehkui 3.8.3+1.14.4-1.21
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		pfm: Paladin's Furniture 1.2.1
		polymorph: Polymorph 0.49.6+1.20.1
			spectrelib: SpectreLib 0.13.16+1.20.1
				com_electronwill_night-config_core: core 3.8.1
				com_electronwill_night-config_toml: toml 3.8.1
		powah: Powah! 5.0.7
		prometheus: Prometheus 1.2.5
		puzzleslib: Puzzles Lib 8.1.23
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		railways: Create: Steam 'n' Rails 1.6.4+fabric-mc1.20.1
		reborncore: Reborn Core 5.8.7
		rechiseled: Rechiseled 1.1.6
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.1-build.101
		resourcefulconfig: Resourcefulconfig 2.1.2
		resourcefullib: Resourceful Lib 2.1.29
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		roughlyenoughitems: Roughly Enough Items 12.1.750
			error_notifier: Error Notifier 1.0.9
		searchables: Searchables 1.0.3
		servercore: ServerCore 1.5.1+1.20.1
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
			org_yaml_snakeyaml: snakeyaml 2.2
			placeholder-api: Placeholder API 2.1.3+1.20.1
			space_arim_dazzleconf_dazzleconf-core: dazzleconf-core 1.3.0-M2
			space_arim_dazzleconf_dazzleconf-ext-snakeyaml: dazzleconf-ext-snakeyaml 1.3.0-M2
		simpleradio: SimpleRadio 2.4.6.1
			polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.19+1.20.1
		simplerpc: Simple RPC 3.3.2
		sodium: Sodium 0.5.11+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.4.5
		spindlemark: SpindleMark 1.1.0
			lib39-core: Lib39 (Core) 1.5.0-experimental5+1.20.1
			lib39-keygen: Lib39 (Keygen) 1.5.0-experimental5+1.20.1
		starlight: Starlight 1.1.2+fabric.dbc156f
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17+a
		supplementaries: Supplementaries 1.20-2.8.17
		tacz: Timeless & Classics Guns: Zero 1.0.2-hotfix3
			com_github_286799714_luaj_luaj-core: luaj-core 3.0.3
			com_github_286799714_luaj_luaj-jse: luaj-jse 3.0.3
			mkb: ModernKeyBinding 1.2.0
			org_apache_commons_commons-math3: commons-math3 3.6.1
			porting_lib_core: Porting Lib Core 2.3.4+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.4+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.4+1.20.1
		techreborn: Tech Reborn 5.8.7
		tempad: Tempad 2.3.4
		terrablender: TerraBlender 3.0.1.7
		terrestria: Terrestria 6.0.13
			terraform-config-api-v1: Terraform Config API (v1) 7.0.3
			terraform-dirt-api-v1: Terraform Dirt API (v1) 7.0.3
			terraform-tree-api-v1: Terraform Tree API (v1) 7.0.3
			terrestria-client: Terrestria: Client 6.0.13
			terrestria-common: Terrestria: Common 6.0.13
			terrestria-worldgen: Terrestria: World Generation 6.0.13
		the_bumblezone: The Bumblezone - Fabric 7.4.18+1.20.1-fabric
			athena: Athena 3.1.1
		theprinter: The Printer 1.4.4+1.20
		thermoo: Thermoo 2.3.2
		threadtweak: ThreadTweak 1.20.2-0.1.1
		touhouorigins: Touhou Origins 1.0.2
		travelersbackpack: Traveler's Backpack fabric-1.20.1-9.1.16
		traverse: Traverse 7.0.12
			traverse-client: Traverse: Client 7.0.12
			traverse-common: Traverse: Common 7.0.12
			traverse-worldgen: Traverse: World Generation 7.0.12
		trinkets: Trinkets 3.7.2
		vinery: [Let's Do] Vinery 1.4.28
		visualworkbench: Visual Workbench 8.0.0
		vmp: Very Many Players 0.2.0+beta.7.102
		voicechat: Simple Voice Chat 1.20.1-2.5.22
		waveycapes: WaveyCapes 1.4.8
		waystones: Waystones 14.1.4
		wilderwild: Wilder Wild 2.4.6-mc1.20.1
			frozenlib: FrozenLib 1.8-mc1.20.1
		windchimes: Windchimes 1.2.4+1.20
		xaerominimap: Xaero's Minimap 24.4.0
		xaeroworldmap: Xaero's World Map 1.39.0
		yungsapi: YUNG's API 1.20-Fabric-4.0.5
			org_javassist_javassist: javassist 3.29.2-GA
		yungsbridges: YUNG's Bridges 1.20-Fabric-4.0.3
		yungsextras: YUNG's Extras 1.20-Fabric-4.0.3
	Loaded Shaderpack: (off)
	Flywheel Backend: Uninitialized
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3050/PCIe/SSE2 GL version 3.2.0 NVIDIA 555.99, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 12x AMD Ryzen 5 5600G with Radeon Graphics```

**Comment by ChrysanthCow** [comment]
looks like a problem with both in mind.
I'll get a fix out eventually, but keep in mind that I am pretty tired of maintaining this mod, so it may take a while.
